name: jupyter_jsmol-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - nodejs
  - yarn
  - jupyter
  - jupyterlab
  - ipywidgets
  - jupyter-packaging
  - ase
  - pymatgen
  - pip
  - pip:
    - jupyter_jsmol
